### PR TITLE
generate automatic API docs w/ jsdoc

### PR DESCRIPTION
**Pull request by rhelmer**
This adds an `npm run docs` command to generate API docs using jsdoc, it creates a `./jsdoc` directory for this.

- [x] add npm command to generate jsdoc
- [x] set up CircleCI to push to GH docs

### CODE REVIEW

**Comment by rhelmer** [comment]
I've just manually updated the `gh-pages` branch to match fde5434c36940d196ada19928f7f6a9cd1282c89, and brought this PR up-to-date. It just needs the Circle CI deploy bit done.

Circle has docs for this: https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/

**Comment by rhelmer** [comment]
We could probably use GH actions here instead of CircleCI:
https://github.com/marketplace?type=actions&query=github+pages

I'm not as familiar with GH actions, will take a look. It might be easier for folks that don't have Circle access to manage.

**Comment by rhelmer** [comment]
@jonathanmayer This branch adds building and auto-deployment of JSDoc, with some minor cleanup/modernization of the CircleCI config.

**Review by jonathanmayer — APPROVED** [review]

**Comment by rhelmer** [comment]
OK I've moved the jsdocs into their own subdir on the gh-pages, as discussed: https://mozilla-rally.github.io/web-science/

**Pull request merged**
